default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: db

development:
  <<: *default
  database: pai_kakaku_dev

test:
  <<: *default
  database: pai_kakaku_test

production:
  <<: *default
  database: pai_kakaku_production
  username: pai_kakaku
  password: <%= ENV["PAI_KAKAKU_DATABASE_PASSWORD"] %>
